<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="3.5" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<GallioProjectOutputPath>..\Gallio\bin</GallioProjectOutputPath>
		<TargetConfig>$(TargetPath).config</TargetConfig>
		<TargetPdb>$(OutputPath)$(TargetName).pdb</TargetPdb>
		<OriginalConfig>$(TargetFileName).config</OriginalConfig>
		<IntermediateTargetPath>$(IntermediateOutputPath)$(TargetFileName)</IntermediateTargetPath>
		<IntermediateTargetPdb>$(IntermediateOutputPath)$(TargetName).pdb</IntermediateTargetPdb>

		<!-- Disable manifest embedding to avoid mt.exe issues -->
		<EmbedManifest>false</EmbedManifest>
	</PropertyGroup>

	<PropertyGroup>
		<CorflagsToolPath>bin\NETFX 4.8 Tools\</CorflagsToolPath>
		<CorflagsToolPath Condition="'$(Platform)' != 'AnyCPU'">$(CorflagsToolPath)$(Platform)\</CorflagsToolPath>
	</PropertyGroup>

	<ItemGroup>
		<HostVariant Include="bin\Gallio.Host.exe">
			<Self>true</Self>
		</HostVariant>

		<HostVariant Include="bin\Gallio.Host.x86.exe">
			<CorFlags>/32BIT+</CorFlags>
		</HostVariant>

		<HostVariant Include="bin\Gallio.Host.Elevated.exe" />

		<HostVariant Include="bin\Gallio.Host.Elevated.x86.exe">
			<CorFlags>/32BIT+</CorFlags>
		</HostVariant>

		<HostTargetFile Include="@(HostVariant)">
			<SourceFile>$(TargetPath)</SourceFile>
		</HostTargetFile>

		<HostTargetFile Include="@(HostVariant->'%(RootDir)%(Directory)%(Filename).pdb')">
			<SourceFile>$(TargetPdb)</SourceFile>
		</HostTargetFile>
	</ItemGroup>

	<Target Name="_PopulateHostTargetFileExceptSelf">
		<CreateItem Include="@(HostTargetFile)"
					Condition="'%(HostTargetFile.Self)'!='true'">
			<Output TaskParameter="Include" ItemName="HostTargetFileExceptSelf" />
		</CreateItem>
	</Target>

	<Target Name="AfterClean" DependsOnTargets="_PopulateHostTargetFileExceptSelf">
		<Delete Files="@(HostTargetFileExceptSelf)" Condition="Exists('%(Identity)')" />
	</Target>

	<Target Name="AfterBuild" DependsOnTargets="_PopulateHostTargetFileExceptSelf" Inputs="$(IntermediateTargetPath);$(OriginalConfig)" Outputs="@(HostVariant)">
		<!-- Make extra copies for each variant -->
		<Copy SourceFiles="@(HostTargetFileExceptSelf->'%(SourceFile)')" DestinationFiles="@(HostTargetFileExceptSelf)">
			<Output TaskParameter="DestinationFiles" ItemName="FilesWrites" />
		</Copy>

		<!-- Patch 32-bit flags if needed -->
		<Exec Command="&quot;$(TargetFrameworkSDKDirectory)$(CorflagsToolPath)corflags.exe&quot; /force &quot;%(HostVariant.FullPath)&quot; /nologo %(HostVariant.CorFlags)" Condition="'%(HostVariant.CorFlags)'!=''" />

		<!-- Copy variants into Gallio bin folder for local debugging -->
		<Copy SourceFiles="@(HostTargetFile)" DestinationFolder="$(GallioProjectOutputPath)">
			<Output TaskParameter="DestinationFiles" ItemName="FilesWrites" />
		</Copy>

		<!-- Touch outputs -->
		<Touch Files="@(HostTargetFile)" />
		<Copy SourceFiles="$(TargetPath)" DestinationFiles="$(IntermediateTargetPath)" />
	</Target>
</Project>

